Algoritmo "par_ou_impar"
// Professor : Cintia pinho
// Descrição   : verificar se o número digitado pelo usuário é par ou ímpar
// Autor(a)    : Júlia Araújo
// Data atual  : 02/08/2022
var
numero: inteiro

Inicio
// entrada
escreval("Digite um número")
leia(numero)

//processamento
se (numero mod 2=0)entao
 escreval("O número digitado é par")
senao
  escreval("O número digitado é ímpar")
fimse


Fimalgoritmo