Algoritmo "areatriangulo"
// Descrição   : solicita base e altura e calcula a area do triangulo
// Autor(a)    : Júlia Araújo
// Data atual  : 08/03/2022
Var
base, alt, area:real


Inicio
//entrada
escreval("Digite a base do triangulo: ")
leia(base)
escreval("Digite a altura do triangulo: ")
leia(alt)

//processamento
area <- (base*alt)/2

//saida

escreval("A área do triangulo é: ", area)

Fimalgoritmo