Algoritmo "mediadosnumeros"
// Descrição   : solicita n1,n2,n3
// Autor(a)    : Júlia Araújo
// Data atual  : 08/03/2022
Var
n1,n2,n3, media: real

Inicio
//entrada
escreval("Digite o primeiro número: ")
leia(n1)
escreval("Digite o segundo número:")
leia(n2)
escreval("Digite o terceiro número:")
leia(n3)

//processamento
media <- (n1+n2+n3)/3

//saida

escreval("A média dos tres números é: ", media)

Fimalgoritmo