algoritmo "conversaohoras"
// Função : Solicitar horas e minutos para converter em segundos
// Autor : Júlia Araújo
// Data : 10/05/2022
// Seção de Declarações 
var
horas, min, seg, total: real

inicio
//entrada
escreval("Digite as horas que deseja converter:")
leia(horas)
escreval("Digite os minutos")
leia(min)

//processamento
seg <- (minutos/60)+horas

//saída
escreval("Os segundos convertidos são:", segundos)

fimalgoritmo
